language: python
python:
- '2.7'
install: 
  - pip install -q -r requirements.txt
branches:
  only:
    - master
script:
  - mkdocs build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_API_TOKEN
  project: "personal-site-941e8"
